
create table cache_produto (
    cache_key varchar(255) not null,
    cache_name varchar(255),
    cache_type varchar(255),
    cache_value jsonb,
    expires_at timestamp(6),
    primary key (cache_key)
);

create index idx_cache_lookup on cache_produto (cache_name, cache_key)

create table produto (
    id bigint generated by default as identity,
    nome varchar(255),
    preco numeric(38,2),
    primary key (id)
);